version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RS
  web:
    image: httpd:2.4.51
    restart: on-failure
    volumes:
      - ./src/:/usr/
    restart: on-failure
