version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RS
  web:
    image: webdevops/php-apache:latest
    restart: on-failure
    volumes:
      - ./src/:/app/
    restart: on-failure
